// ============================================================
// Annotated C# for SampleProfile
// Generated by CIMTool https://cimtool.ucaiug.io [cimtool.ucaiug.io]
// 
// DO NOT EDIT - this file is fully regenerated by CIMTool on
// every build. Hand-written customisations belong in partial
// class files alongside this one.
// ============================================================

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

/// <summary>
/// Entity Framework Core entity classes generated from the
/// <b>CoreEquipment</b> CIMTool profile.
/// </summary>
/// <remarks>
/// <para>
/// <b>No <c>ICollection&lt;T&gt;</c> Properties - Intentional Design</b><br/>
/// Collection-valued inverse navigation properties
/// (<c>ICollection&lt;T&gt;</c>) are intentionally not generated.
/// Single-valued foreign-key relationships are fully mapped; inverse
/// one-to-many collections are omitted by design, not by omission.
/// EF Core does not require them to configure or resolve a relationship.
/// They are excluded because:
/// <list type="bullet">
///    <item>
///      CIM associations are unbounded by definition. Materialising an
///      unbounded <c>ICollection&lt;T&gt;</c> into memory with no pagination
///      is a runtime hazard for large profiles such as CGMES CoreEquipment.
///    </item>
///    <item>
///      They introduce circular-reference risk during JSON serialisation
///      with <c>System.Text.Json</c> or <c>Newtonsoft.Json</c> unless
///      reference handling is explicitly configured.
///    </item>
///    <item>
///      Inverse associations are profile-dependent and not present in all
///      profiles, making generated <c>ICollection&lt;T&gt;</c> properties
///      inconsistent across profiles.
///    </item>
///    <item>
///      Bidirectional EF Core mappings require both sides to be kept
///      in sync on every add/remove, adding fragility to consumer code.
///    </item>
///    <item>
///      Explicit LINQ queries support pagination, filtering, and sorting
///      that a generated collection property never can.
///    </item>
///  </list>
/// To navigate from a parent entity to its children, query through
/// the child side using LINQ:
/// <code>
/// // All children for a given parent (via shadow FK):
/// var units = context.Set<PowerElectronicsUnit>()
/// .Where(u => u.PowerElectronicsConnectionId == connection.MRId)
/// .ToList();
/// 
/// // With pagination for large result sets:
/// var equipment = context.Set<Equipment>()
/// .Where(e => e.EquipmentContainerId == substation.MRId)
/// .Skip(0).Take(100).ToList();
/// </code>
/// Consumers who need inverse navigation for specific patterns can add
/// <c>ICollection&lt;T&gt;</c> properties non-destructively via
/// <c>partial class</c> declarations without modifying this generated file.
/// </para>
/// <para>
/// <b>Compound Type References</b><br/>
/// CIM Compound types are treated as value objects - each compound row has
/// exactly one owner and is never shared across parent columns or rows.
/// Each compound reference is represented as a shadow FK string property
/// (e.g. <c>ElectronicAddressId</c>) paired with a nullable navigation
/// property (e.g. <c>ElectronicAddress?</c>).
/// The companion SQL DDL emits <c>ON DELETE CASCADE</c> for every compound FK,
/// and the generated <c>ModelConfiguration</c> applies
/// <c>DeleteBehavior.Cascade</c> for compound relationships so EF Core treats
/// compound references as owned-like one-to-one links in its relationship metadata.
/// However, when the FK column lives on the owner row, EF Core does not by itself
/// perform owner-side orphan cleanup during replacement or parent deletion. If you need
/// full compound ownership cleanup parity with the companion SQL DDL, add a
/// <c>SaveChanges</c> override or interceptor that deletes now-unreferenced
/// compound rows after the owner changes are saved.
/// Each compound entity constructor assigns a new <see cref="System.Guid"/>
/// to its <c>Id</c> property on instantiation.
/// </para>
/// <para>
/// <b>DbContext Integration</b><br/>
/// This file includes a generated <c>ModelConfiguration</c> nested static
/// class containing the complete EF Core Fluent API configuration for all
/// entities in this profile. Create the following DbContext subclass once
/// in your project - it will not be overwritten by CIMTool:
/// <code>
/// public class SampleProfileDbContext : DbContext
/// {
///     // Add one DbSet<T> per entity class, e.g.:
///     // public DbSet<SampleProfile.Organisation> Organisations { get; set; } = null!;
///     
///     public SampleProfileDbContext(DbContextOptions options) : base(options) { }
///     
///     protected override void OnModelCreating(ModelBuilder modelBuilder)
///     {
///         SampleProfile.ModelConfiguration.ConfigureModel(modelBuilder);
///     }
///     
///     // If you need owner-side compound cleanup parity with the companion DDL,
///     // add a SaveChanges override or interceptor that deletes now-unreferenced
///     // compound rows after owner updates and deletes are saved.
/// }
/// </code>
/// </para>
/// </remarks>
public class SampleProfile
{
    /// <summary>
    /// Defines the current status of the Crew - assigned, arrived, etc.
    /// </summary>
    [Table("CrewStatusKind")]
    public class CrewStatusKind
    {
        public CrewStatusKind() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>CrewStatusKind</c> enumeration literal, compared by <c>Name</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>CrewStatusKind</c> with the same
        /// non-null <c>Name</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Enumeration types are lookup tables keyed on <c>Name</c>. Returning
        /// <c>false</c> when <c>Name</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not CrewStatusKind other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name != null && Name == other.Name;
        }
        /// <summary>
        /// Returns a hash code based on the <c>Name</c> of this enumeration literal.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Name</c>, or zero if <c>Name</c> is <c>null</c>,
        /// consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
        [Key]
        [Column("name")]
        [MaxLength(100)]
        public string Name { get; set; } = null!;
        public const string arrived = "arrived";
        public const string assigned = "assigned";
        public const string awaitingCrewAssignment = "awaitingCrewAssignment";
        public const string enroute = "enroute";
        public const string fieldComplete = "fieldComplete";
    }
    /// <summary>
    /// An unordered enumeration of phase identifiers. Allows designation of phases
    /// for both transmission and distribution equipment, circuits and loads. The
    /// enumeration, by itself, does not describe how the phases are connected
    /// together or connected to ground. Ground is not explicitly denoted as a
    /// phase.
    /// Residential and small commercial loads are often served from single-phase,
    /// or split-phase, secondary circuits. For the example of s12N, phases 1 and
    /// 2 refer to hot wires that are 180 degrees out of phase, while N refers
    /// to the neutral wire. Through single-phase transformer connections, these
    /// secondary circuits may be served from one or two of the primary phases
    /// A, B, and C. For three-phase loads, use the A, B, C phase codes instead
    /// of s12N.
    /// The integer values are from IEC 61968-9 to support revenue metering applications.
    /// </summary>
    [Table("PhaseCode")]
    public class PhaseCode
    {
        public PhaseCode() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>PhaseCode</c> enumeration literal, compared by <c>Name</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>PhaseCode</c> with the same
        /// non-null <c>Name</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Enumeration types are lookup tables keyed on <c>Name</c>. Returning
        /// <c>false</c> when <c>Name</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not PhaseCode other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name != null && Name == other.Name;
        }
        /// <summary>
        /// Returns a hash code based on the <c>Name</c> of this enumeration literal.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Name</c>, or zero if <c>Name</c> is <c>null</c>,
        /// consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
        [Key]
        [Column("name")]
        [MaxLength(100)]
        public string Name { get; set; } = null!;
        public const string A = "A";
        public const string AB = "AB";
        public const string ABC = "ABC";
        public const string ABCN = "ABCN";
        public const string ABN = "ABN";
        public const string AC = "AC";
        public const string ACN = "ACN";
        public const string AN = "AN";
        public const string B = "B";
        public const string BC = "BC";
        public const string BCN = "BCN";
        public const string BN = "BN";
        public const string C = "C";
        public const string CN = "CN";
        public const string N = "N";
        public const string X = "X";
        public const string XN = "XN";
        public const string XY = "XY";
        public const string XYN = "XYN";
        public const string none = "none";
        public const string s1 = "s1";
        public const string s12 = "s12";
        public const string s12N = "s12N";
        public const string s1N = "s1N";
        public const string s2 = "s2";
        public const string s2N = "s2N";
    }
    /// <summary>
    /// Kind of control for shunt impedance.
    /// </summary>
    [Table("ShuntImpedanceControlKind")]
    public class ShuntImpedanceControlKind
    {
        public ShuntImpedanceControlKind() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>ShuntImpedanceControlKind</c> enumeration literal, compared by <c>Name</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>ShuntImpedanceControlKind</c> with the same
        /// non-null <c>Name</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Enumeration types are lookup tables keyed on <c>Name</c>. Returning
        /// <c>false</c> when <c>Name</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not ShuntImpedanceControlKind other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name != null && Name == other.Name;
        }
        /// <summary>
        /// Returns a hash code based on the <c>Name</c> of this enumeration literal.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Name</c>, or zero if <c>Name</c> is <c>null</c>,
        /// consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
        [Key]
        [Column("name")]
        [MaxLength(100)]
        public string Name { get; set; } = null!;
        public const string @fixed = "fixed";
        public const string localOnly = "localOnly";
        public const string remoteOnly = "remoteOnly";
        public const string remoteWithLocalOverride = "remoteWithLocalOverride";
    }
    /// <summary>
    /// Kind of local control for shunt impedance.
    /// </summary>
    [Table("ShuntImpedanceLocalControlKind")]
    public class ShuntImpedanceLocalControlKind
    {
        public ShuntImpedanceLocalControlKind() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>ShuntImpedanceLocalControlKind</c> enumeration literal, compared by <c>Name</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>ShuntImpedanceLocalControlKind</c> with the same
        /// non-null <c>Name</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Enumeration types are lookup tables keyed on <c>Name</c>. Returning
        /// <c>false</c> when <c>Name</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not ShuntImpedanceLocalControlKind other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name != null && Name == other.Name;
        }
        /// <summary>
        /// Returns a hash code based on the <c>Name</c> of this enumeration literal.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Name</c>, or zero if <c>Name</c> is <c>null</c>,
        /// consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
        [Key]
        [Column("name")]
        [MaxLength(100)]
        public string Name { get; set; } = null!;
        public const string current = "current";
        public const string none = "none";
        public const string powerFactor = "powerFactor";
        public const string reactivePower = "reactivePower";
        public const string temperature = "temperature";
        public const string time = "time";
        public const string voltage = "voltage";
    }
    /// <summary>
    /// Kind of wire insulation.
    /// </summary>
    [Table("WireInsulationKind")]
    public class WireInsulationKind
    {
        public WireInsulationKind() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>WireInsulationKind</c> enumeration literal, compared by <c>Name</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>WireInsulationKind</c> with the same
        /// non-null <c>Name</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Enumeration types are lookup tables keyed on <c>Name</c>. Returning
        /// <c>false</c> when <c>Name</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not WireInsulationKind other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name != null && Name == other.Name;
        }
        /// <summary>
        /// Returns a hash code based on the <c>Name</c> of this enumeration literal.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Name</c>, or zero if <c>Name</c> is <c>null</c>,
        /// consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
        [Key]
        [Column("name")]
        [MaxLength(100)]
        public string Name { get; set; } = null!;
        public const string asbestosAndVarnishedCambric = "asbestosAndVarnishedCambric";
        public const string beltedPilc = "beltedPilc";
        public const string butyl = "butyl";
        public const string crosslinkedPolyethylene = "crosslinkedPolyethylene";
        public const string ethylenePropyleneRubber = "ethylenePropyleneRubber";
        public const string highMolecularWeightPolyethylene = "highMolecularWeightPolyethylene";
        public const string highPressureFluidFilled = "highPressureFluidFilled";
        public const string lowCapacitanceRubber = "lowCapacitanceRubber";
        public const string oilPaper = "oilPaper";
        public const string other = "other";
        public const string ozoneResistantRubber = "ozoneResistantRubber";
        public const string rubber = "rubber";
        public const string siliconRubber = "siliconRubber";
        public const string treeResistantHighMolecularWeightPolyethylene = "treeResistantHighMolecularWeightPolyethylene";
        public const string treeRetardantCrosslinkedPolyethylene = "treeRetardantCrosslinkedPolyethylene";
        public const string unbeltedPilc = "unbeltedPilc";
        public const string varnishedCambricCloth = "varnishedCambricCloth";
        public const string varnishedDacronGlass = "varnishedDacronGlass";
    }
    /// <summary>
    /// Kind of wire material.
    /// </summary>
    [Table("WireMaterialKind")]
    public class WireMaterialKind
    {
        public WireMaterialKind() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>WireMaterialKind</c> enumeration literal, compared by <c>Name</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>WireMaterialKind</c> with the same
        /// non-null <c>Name</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Enumeration types are lookup tables keyed on <c>Name</c>. Returning
        /// <c>false</c> when <c>Name</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not WireMaterialKind other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name != null && Name == other.Name;
        }
        /// <summary>
        /// Returns a hash code based on the <c>Name</c> of this enumeration literal.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Name</c>, or zero if <c>Name</c> is <c>null</c>,
        /// consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Name?.GetHashCode() ?? 0;
        [Key]
        [Column("name")]
        [MaxLength(100)]
        public string Name { get; set; } = null!;
        public const string aaac = "aaac";
        public const string acsr = "acsr";
        public const string aluminum = "aluminum";
        public const string aluminumAlloy = "aluminumAlloy";
        public const string aluminumAlloySteel = "aluminumAlloySteel";
        public const string aluminumSteel = "aluminumSteel";
        public const string copper = "copper";
        public const string other = "other";
        public const string steel = "steel";
    }
    /// <summary>
    /// Electronic address information.
    /// </summary>
    [Table("ElectronicAddress")]
    public class ElectronicAddress
    {
        /// <summary>
        /// Initialises a new <c>ElectronicAddress</c> and assigns a new UUID to <c>Id</c>,
        /// satisfying the compound value object ownership invariant: each compound row
        /// has exactly one owner and must carry a unique surrogate id that is never
        /// shared across parent columns or parent rows. See the companion
        /// sql-rdfs-ansi92 DDL script for full details.
        /// </summary>
        public ElectronicAddress() { Id = System.Guid.NewGuid().ToString(); }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>ElectronicAddress</c> compound value object, compared by surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>ElectronicAddress</c> with the same
        /// <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Compound types are value objects - each row has exactly one owner and its
        /// <c>Id</c> is a UUID assigned on construction, so <c>Id</c> is never
        /// <c>null</c> and no null guard is required.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not ElectronicAddress other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on the surrogate <c>Id</c> of this instance.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Id</c>, consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Id.GetHashCode();
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// Primary email address.
        /// </summary>
        [Column("email1")]
        [MaxLength(255)]
        public string? Email1 { get; set; }
        /// <summary>
        /// Alternate email address.
        /// </summary>
        [Column("email2")]
        [MaxLength(255)]
        public string? Email2 { get; set; }
        /// <summary>
        /// Address on local area network.
        /// </summary>
        [Column("lan")]
        [MaxLength(255)]
        public string? Lan { get; set; }
        /// <summary>
        /// MAC (Media Access Control) address.
        /// </summary>
        [Column("mac")]
        [MaxLength(255)]
        public string? Mac { get; set; }
        /// <summary>
        /// Password needed to log in.
        /// </summary>
        [Column("password")]
        [MaxLength(255)]
        public string? Password { get; set; }
        /// <summary>
        /// Radio address.
        /// </summary>
        [Column("radio")]
        [MaxLength(255)]
        public string? Radio { get; set; }
        /// <summary>
        /// User ID needed to log in, which can be for an individual person, an organisation,
        /// a location, etc.
        /// </summary>
        [Column("userID")]
        [MaxLength(255)]
        public string? UserID { get; set; }
        /// <summary>
        /// World wide web address.
        /// </summary>
        [Column("web")]
        [MaxLength(255)]
        public string? Web { get; set; }
    }
    /// <summary>
    /// Current status information relevant to an entity.
    /// </summary>
    [Table("Status")]
    public class Status
    {
        /// <summary>
        /// Initialises a new <c>Status</c> and assigns a new UUID to <c>Id</c>,
        /// satisfying the compound value object ownership invariant: each compound row
        /// has exactly one owner and must carry a unique surrogate id that is never
        /// shared across parent columns or parent rows. See the companion
        /// sql-rdfs-ansi92 DDL script for full details.
        /// </summary>
        public Status() { Id = System.Guid.NewGuid().ToString(); }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>Status</c> compound value object, compared by surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>Status</c> with the same
        /// <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Compound types are value objects - each row has exactly one owner and its
        /// <c>Id</c> is a UUID assigned on construction, so <c>Id</c> is never
        /// <c>null</c> and no null guard is required.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not Status other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on the surrogate <c>Id</c> of this instance.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Id</c>, consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Id.GetHashCode();
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// Date and time for which status 'value' applies.
        /// </summary>
        [Column("dateTime")]
        public DateTime? DateTimeValue { get; set; }
        /// <summary>
        /// Reason code or explanation for why an object went to the current status
        /// 'value'.
        /// </summary>
        [Column("reason")]
        [MaxLength(255)]
        public string? Reason { get; set; }
        /// <summary>
        /// Pertinent information regarding the current 'value', as free form text.
        /// </summary>
        [Column("remark")]
        [MaxLength(255)]
        public string? Remark { get; set; }
        /// <summary>
        /// Status value at 'dateTime'; prior status changes may have been kept in
        /// instances of activity records associated with the object to which this
        /// status applies.
        /// </summary>
        [Column("value")]
        [MaxLength(255)]
        public string? Value { get; set; }
    }
    /// <summary>
    /// Street details, in the context of address.
    /// </summary>
    [Table("StreetDetail")]
    public class StreetDetail
    {
        /// <summary>
        /// Initialises a new <c>StreetDetail</c> and assigns a new UUID to <c>Id</c>,
        /// satisfying the compound value object ownership invariant: each compound row
        /// has exactly one owner and must carry a unique surrogate id that is never
        /// shared across parent columns or parent rows. See the companion
        /// sql-rdfs-ansi92 DDL script for full details.
        /// </summary>
        public StreetDetail() { Id = System.Guid.NewGuid().ToString(); }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>StreetDetail</c> compound value object, compared by surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>StreetDetail</c> with the same
        /// <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Compound types are value objects - each row has exactly one owner and its
        /// <c>Id</c> is a UUID assigned on construction, so <c>Id</c> is never
        /// <c>null</c> and no null guard is required.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not StreetDetail other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on the surrogate <c>Id</c> of this instance.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Id</c>, consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Id.GetHashCode();
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// First line of a free form address or some additional address information
        /// (for example a mail stop).
        /// </summary>
        [Column("addressGeneral")]
        [MaxLength(255)]
        public string? AddressGeneral { get; set; }
        /// <summary>
        /// (if applicable) Second line of a free form address.
        /// </summary>
        [Column("addressGeneral2")]
        [MaxLength(255)]
        public string? AddressGeneral2 { get; set; }
        /// <summary>
        /// (if applicable) Third line of a free form address.
        /// </summary>
        [Column("addressGeneral3")]
        [MaxLength(255)]
        public string? AddressGeneral3 { get; set; }
        /// <summary>
        /// (if applicable) In certain cases the physical location of the place of
        /// interest does not have a direct point of entry from the street, but may
        /// be located inside a larger structure such as a building, complex, office
        /// block, apartment, etc.
        /// </summary>
        [Column("buildingName")]
        [MaxLength(255)]
        public string? BuildingName { get; set; }
        /// <summary>
        /// (if applicable) Utilities often make use of external reference systems,
        /// such as those of the town-planner's department or surveyor general's mapping
        /// system, that allocate global reference codes to streets.
        /// </summary>
        [Column("code")]
        [MaxLength(255)]
        public string? Code { get; set; }
        /// <summary>
        /// The identification by name or number, expressed as text, of the floor in
        /// the building as part of this address.
        /// </summary>
        [Column("floorIdentification")]
        [MaxLength(255)]
        public string? FloorIdentification { get; set; }
        /// <summary>
        /// Name of the street.
        /// </summary>
        [Column("name")]
        [MaxLength(255)]
        public string? Name { get; set; }
        /// <summary>
        /// Designator of the specific location on the street.
        /// </summary>
        [Column("number")]
        [MaxLength(255)]
        public string? Number { get; set; }
        /// <summary>
        /// Prefix to the street name. For example: North, South, East, West.
        /// </summary>
        [Column("prefix")]
        [MaxLength(255)]
        public string? Prefix { get; set; }
        /// <summary>
        /// Suffix to the street name. For example: North, South, East, West.
        /// </summary>
        [Column("suffix")]
        [MaxLength(255)]
        public string? Suffix { get; set; }
        /// <summary>
        /// Number of the apartment or suite.
        /// </summary>
        [Column("suiteNumber")]
        [MaxLength(255)]
        public string? SuiteNumber { get; set; }
        /// <summary>
        /// Type of street. Examples include: street, circle, boulevard, avenue, road,
        /// drive, etc.
        /// </summary>
        [Column("type")]
        [MaxLength(255)]
        public string? Type { get; set; }
        /// <summary>
        /// True if this street is within the legal geographical boundaries of the
        /// specified town (default).
        /// </summary>
        [Column("withinTownLimits")]
        public bool? WithinTownLimits { get; set; }
    }
    /// <summary>
    /// Telephone number.
    /// </summary>
    [Table("TelephoneNumber")]
    public class TelephoneNumber
    {
        /// <summary>
        /// Initialises a new <c>TelephoneNumber</c> and assigns a new UUID to <c>Id</c>,
        /// satisfying the compound value object ownership invariant: each compound row
        /// has exactly one owner and must carry a unique surrogate id that is never
        /// shared across parent columns or parent rows. See the companion
        /// sql-rdfs-ansi92 DDL script for full details.
        /// </summary>
        public TelephoneNumber() { Id = System.Guid.NewGuid().ToString(); }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>TelephoneNumber</c> compound value object, compared by surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>TelephoneNumber</c> with the same
        /// <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Compound types are value objects - each row has exactly one owner and its
        /// <c>Id</c> is a UUID assigned on construction, so <c>Id</c> is never
        /// <c>null</c> and no null guard is required.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not TelephoneNumber other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on the surrogate <c>Id</c> of this instance.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Id</c>, consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Id.GetHashCode();
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// (if applicable) Area or region code.
        /// </summary>
        [Column("areaCode")]
        [MaxLength(255)]
        public string? AreaCode { get; set; }
        /// <summary>
        /// City code.
        /// </summary>
        [Column("cityCode")]
        [MaxLength(255)]
        public string? CityCode { get; set; }
        /// <summary>
        /// Country code.
        /// </summary>
        [Column("countryCode")]
        [MaxLength(255)]
        public string? CountryCode { get; set; }
        /// <summary>
        /// (if applicable) Dial out code, for instance to call outside an enterprise.
        /// </summary>
        [Column("dialOut")]
        [MaxLength(255)]
        public string? DialOut { get; set; }
        /// <summary>
        /// (if applicable) Extension for this telephone number.
        /// </summary>
        [Column("extension")]
        [MaxLength(255)]
        public string? Extension { get; set; }
        /// <summary>
        /// (if applicable) Prefix used when calling an international number.
        /// </summary>
        [Column("internationalPrefix")]
        [MaxLength(255)]
        public string? InternationalPrefix { get; set; }
        /// <summary>
        /// Phone number according to International Telecommunication Union (ITU) E.164.
        /// </summary>
        [Column("ituPhone")]
        [MaxLength(255)]
        public string? ItuPhone { get; set; }
        /// <summary>
        /// Main (local) part of this telephone number.
        /// </summary>
        [Column("localNumber")]
        [MaxLength(255)]
        public string? LocalNumber { get; set; }
    }
    /// <summary>
    /// Town details, in the context of address.
    /// </summary>
    [Table("TownDetail")]
    public class TownDetail
    {
        /// <summary>
        /// Initialises a new <c>TownDetail</c> and assigns a new UUID to <c>Id</c>,
        /// satisfying the compound value object ownership invariant: each compound row
        /// has exactly one owner and must carry a unique surrogate id that is never
        /// shared across parent columns or parent rows. See the companion
        /// sql-rdfs-ansi92 DDL script for full details.
        /// </summary>
        public TownDetail() { Id = System.Guid.NewGuid().ToString(); }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>TownDetail</c> compound value object, compared by surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>TownDetail</c> with the same
        /// <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Compound types are value objects - each row has exactly one owner and its
        /// <c>Id</c> is a UUID assigned on construction, so <c>Id</c> is never
        /// <c>null</c> and no null guard is required.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not TownDetail other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on the surrogate <c>Id</c> of this instance.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Id</c>, consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Id.GetHashCode();
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// Town code.
        /// </summary>
        [Column("code")]
        [MaxLength(255)]
        public string? Code { get; set; }
        /// <summary>
        /// Name of the country.
        /// </summary>
        [Column("country")]
        [MaxLength(255)]
        public string? Country { get; set; }
        /// <summary>
        /// Town name.
        /// </summary>
        [Column("name")]
        [MaxLength(255)]
        public string? Name { get; set; }
        /// <summary>
        /// Town section. For example, it is common for there to be 36 sections per
        /// township.
        /// </summary>
        [Column("section")]
        [MaxLength(255)]
        public string? Section { get; set; }
        /// <summary>
        /// Name of the state or province.
        /// </summary>
        [Column("stateOrProvince")]
        [MaxLength(255)]
        public string? StateOrProvince { get; set; }
    }
    /// <summary>
    /// General purpose street and postal address information.
    /// </summary>
    [Table("StreetAddress")]
    [Index(nameof(StatusId), IsUnique = true)]
    [Index(nameof(StreetDetailId), IsUnique = true)]
    [Index(nameof(TownDetailId), IsUnique = true)]
    public class StreetAddress
    {
        /// <summary>
        /// Initialises a new <c>StreetAddress</c> and assigns a new UUID to <c>Id</c>,
        /// satisfying the compound value object ownership invariant: each compound row
        /// has exactly one owner and must carry a unique surrogate id that is never
        /// shared across parent columns or parent rows. See the companion
        /// sql-rdfs-ansi92 DDL script for full details.
        /// </summary>
        public StreetAddress() { Id = System.Guid.NewGuid().ToString(); }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>StreetAddress</c> compound value object, compared by surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is a <c>StreetAddress</c> with the same
        /// <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// Compound types are value objects - each row has exactly one owner and its
        /// <c>Id</c> is a UUID assigned on construction, so <c>Id</c> is never
        /// <c>null</c> and no null guard is required.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not StreetAddress other) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on the surrogate <c>Id</c> of this instance.
        /// </summary>
        /// <returns>
        /// The hash code of <c>Id</c>, consistent with the <see cref="Equals"/> override.
        /// </returns>
        public override int GetHashCode() => Id.GetHashCode();
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// The language in which the address is specified, using ISO 639-1 two digit
        /// language code.
        /// </summary>
        [Column("language")]
        [MaxLength(255)]
        public string? Language { get; set; }
        /// <summary>
        /// Post office box.
        /// </summary>
        [Column("poBox")]
        [MaxLength(255)]
        public string? PoBox { get; set; }
        /// <summary>
        /// Postal code for the address.
        /// </summary>
        [Column("postalCode")]
        [MaxLength(255)]
        public string? PostalCode { get; set; }
        /// <summary>
        /// Status of this address.
        /// </summary>
        [Column("status")]
        [MaxLength(100)]
        public string? StatusId { get; set; }
        [ForeignKey(nameof(StatusId))]
        public virtual Status? Status { get; set; }
        /// <summary>
        /// Street detail.
        /// </summary>
        [Column("streetDetail")]
        [MaxLength(100)]
        public string? StreetDetailId { get; set; }
        [ForeignKey(nameof(StreetDetailId))]
        public virtual StreetDetail? StreetDetail { get; set; }
        /// <summary>
        /// Town detail.
        /// </summary>
        [Column("townDetail")]
        [MaxLength(100)]
        public string? TownDetailId { get; set; }
        [ForeignKey(nameof(TownDetailId))]
        public virtual TownDetail? TownDetail { get; set; }
    }
    /// <summary>
    /// This is a root class to provide common identification for all classes needing
    /// identification and naming attributes.
    /// </summary>
    [Table("IdentifiedObject")]
    public class IdentifiedObject
    {
        public IdentifiedObject() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// IdentifiedObject, compared by runtime type and <c>MRId</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is the same concrete type as this instance
        /// and both have an equal, non-null <c>MRId</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// The runtime-type guard ensures two different subclasses with coincidentally
        /// identical UUIDs are never considered equal. Returning <c>false</c> when
        /// <c>MRId</c> is <c>null</c> is consistent with the EF Core convention that a
        /// transient (not-yet-persisted) entity is not equal to any other entity.
        /// All subclasses inherit this implementation and must not override it.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not IdentifiedObject other) return false;
            if (ReferenceEquals(this, other)) return true;
            if (GetType() != other.GetType()) return false;
            return MRId != null && MRId == other.MRId;
        }
        /// <summary>
        /// Returns a hash code based on runtime type and <c>MRId</c>.
        /// </summary>
        /// <returns>
        /// A hash code combining the runtime type and <c>MRId</c>, consistent with
        /// the <see cref="Equals"/> override. All subclasses inherit this implementation.
        /// </returns>
        public override int GetHashCode() => HashCode.Combine(GetType(), MRId);
        /// <summary>
        /// Master resource identifier issued by a model authority. The mRID is unique
        /// within an exchange context. Global uniqueness is easily achieved by using
        /// a UUID, as specified in RFC 4122, for the mRID. The use of UUID is strongly
        /// recommended.
        /// For CIMXML data files in RDF syntax conforming to IEC 61970-552, the mRID
        /// is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.
        /// </summary>
        [Key]
        [Column("mRID")]
        [MaxLength(100)]
        public string MRId { get; set; } = null!;
        /// <summary>
        /// The name is any free human readable and possibly non unique text naming
        /// the object.
        /// </summary>
        [Column("name")]
        [MaxLength(255)]
        public string? Name { get; set; }
    }
    /// <summary>
    /// Distribution capacitor bank control settings.
    /// </summary>
    [Table("ShuntCompensatorControl")]
    public class ShuntCompensatorControl
    {
        public ShuntCompensatorControl() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Determines whether this instance and a specified object represent the same
        /// <c>ShuntCompensatorControl</c>, compared by runtime type and surrogate <c>Id</c>.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with this instance.
        /// </param>
        /// <returns>
        /// <c>true</c> if <paramref name="obj"/> is the same concrete type as this instance
        /// and both have an equal, non-null surrogate <c>Id</c>; otherwise <c>false</c>.
        /// </returns>
        /// <remarks>
        /// This class uses a surrogate <c>Id</c> rather than a natural <c>MRId</c>
        /// because it does not inherit from IdentifiedObject. The runtime-type guard
        /// ensures subclasses with the same surrogate <c>Id</c> are not considered equal.
        /// Returning <c>false</c> when <c>Id</c> is <c>null</c> is consistent with the
        /// convention that a transient entity is not equal to any other entity.
        /// Subclasses inherit this implementation and must not override it.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not ShuntCompensatorControl other) return false;
            if (ReferenceEquals(this, other)) return true;
            if (GetType() != other.GetType()) return false;
            return Id != null && Id == other.Id;
        }
        /// <summary>
        /// Returns a hash code based on runtime type and surrogate <c>Id</c>.
        /// </summary>
        /// <returns>
        /// A hash code combining the runtime type and <c>Id</c>, consistent with
        /// the <see cref="Equals"/> override. Subclasses inherit this implementation.
        /// </returns>
        public override int GetHashCode() => HashCode.Combine(GetType(), Id);
        /// <summary>
        /// Surrogate primary key - this class does not inherit from IdentifiedObject
        /// and has no natural single-column primary key. This surrogate 'id' is a
        /// persistence artefact. The [Index] above enforces a heuristic uniqueness
        /// constraint across all required non-surrogate columns as a guard against
        /// semantically corrupt duplicate rows. See the template documentation in
        /// the XSLT source for a full explanation of the design tradeoffs.
        /// </summary>
        [Key]
        [Column("id")]
        [MaxLength(100)]
        public string Id { get; set; } = null!;
        /// <summary>
        /// Phases that are measured for controlling the device.
        /// </summary>
        [Column("sensingPhaseCode")]
        [MaxLength(100)]
        public string? SensingPhaseCode { get; set; }
    }
    /// <summary>
    /// Set of attributes of an asset, representing typical datasheet information
    /// of a physical device that can be instantiated and shared in different data
    /// exchange contexts:
    /// - as attributes of an asset instance (installed or in stock)
    /// - as attributes of an asset model (product by a manufacturer)
    /// - as attributes of a type asset (generic type of an asset as used in designs/extension
    /// planning).
    /// </summary>
    [Table("AssetInfo")]
    public class AssetInfo : IdentifiedObject
    {
        // Inherits from IdentifiedObject - configure further in EF Fluent API if needed
        public AssetInfo() { }
        public override string ToString() { return this.GetType().Name; }
    }
    /// <summary>
    /// Organisation that might have roles as utility, contractor, supplier, manufacturer,
    /// customer, etc.
    /// </summary>
    [Table("Organisation")]
    [Index(nameof(ElectronicAddressId), IsUnique = true)]
    [Index(nameof(Phone1Id), IsUnique = true)]
    [Index(nameof(Phone2Id), IsUnique = true)]
    [Index(nameof(PostalAddressId), IsUnique = true)]
    [Index(nameof(StreetAddressId), IsUnique = true)]
    public class Organisation : IdentifiedObject
    {
        // Inherits from IdentifiedObject - configure further in EF Fluent API if needed
        public Organisation() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Electronic address.
        /// </summary>
        [Column("electronicAddress")]
        [MaxLength(100)]
        public string? ElectronicAddressId { get; set; }
        [ForeignKey(nameof(ElectronicAddressId))]
        public virtual ElectronicAddress? ElectronicAddress { get; set; }
        /// <summary>
        /// Parent organisation of this organisation.
        /// </summary>
        [Column("ParentOrganisation")]
        [MaxLength(100)]
        public string? ParentOrganisationId { get; set; }
        [ForeignKey(nameof(ParentOrganisationId))]
        public virtual ParentOrganization? ParentOrganisation { get; set; }
        /// <summary>
        /// Phone number.
        /// </summary>
        [Column("phone1")]
        [MaxLength(100)]
        public string? Phone1Id { get; set; }
        [ForeignKey(nameof(Phone1Id))]
        public virtual TelephoneNumber? Phone1 { get; set; }
        /// <summary>
        /// Additional phone number.
        /// </summary>
        [Column("phone2")]
        [MaxLength(100)]
        public string? Phone2Id { get; set; }
        [ForeignKey(nameof(Phone2Id))]
        public virtual TelephoneNumber? Phone2 { get; set; }
        /// <summary>
        /// Postal address, potentially different than 'streetAddress' (e.g., another
        /// city).
        /// </summary>
        [Column("postalAddress")]
        [MaxLength(100)]
        public string? PostalAddressId { get; set; }
        [ForeignKey(nameof(PostalAddressId))]
        public virtual StreetAddress? PostalAddress { get; set; }
        /// <summary>
        /// Street address.
        /// </summary>
        [Column("streetAddress")]
        [MaxLength(100)]
        public string? StreetAddressId { get; set; }
        [ForeignKey(nameof(StreetAddressId))]
        public virtual StreetAddress? StreetAddress { get; set; }
    }
    [Table("ParentOrganization")]
    public class ParentOrganization : Organisation
    {
        // Inherits from Organisation - configure further in EF Fluent API if needed
        public ParentOrganization() { }
        public override string ToString() { return this.GetType().Name; }
    }
    /// <summary>
    /// Properties of shunt capacitor, shunt reactor or switchable bank of shunt
    /// capacitor or reactor assets.
    /// </summary>
    [Table("ShuntCompensatorInfo")]
    public class ShuntCompensatorInfo : AssetInfo
    {
        // Inherits from AssetInfo - configure further in EF Fluent API if needed
        public ShuntCompensatorInfo() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// Maximum allowed apparent power loss.
        /// </summary>
        [Column("maxPowerLoss")]
        public double? MaxPowerLoss { get; set; }
        /// <summary>
        /// Rated current.
        /// </summary>
        [Column("ratedCurrent")]
        public double? RatedCurrent { get; set; }
        /// <summary>
        /// Rated reactive power.
        /// </summary>
        [Column("ratedReactivePower")]
        public double? RatedReactivePower { get; set; }
        /// <summary>
        /// Rated voltage.
        /// </summary>
        [Column("ratedVoltage")]
        public double? RatedVoltage { get; set; }
        [Column("ShuntCompensatorControl")]
        [MaxLength(100)]
        public string? ShuntCompensatorControlId { get; set; }
        [ForeignKey(nameof(ShuntCompensatorControlId))]
        public virtual ShuntCompensatorControl? ShuntCompensatorControl { get; set; }
    }
    /// <summary>
    /// Wire data that can be specified per line segment phase, or for the line
    /// segment as a whole in case its phases all have the same wire characteristics.
    /// </summary>
    [Table("WireInfo")]
    public class WireInfo : AssetInfo
    {
        // Inherits from AssetInfo - configure further in EF Fluent API if needed
        public WireInfo() { }
        public override string ToString() { return this.GetType().Name; }
        /// <summary>
        /// (if there is a different core material) Radius of the central core.
        /// </summary>
        [Column("coreRadius")]
        public double? CoreRadius { get; set; }
        /// <summary>
        /// (if used) Number of strands in the steel core.
        /// </summary>
        [Column("coreStrandCount")]
        public int? CoreStrandCount { get; set; }
        /// <summary>
        /// Geometric mean radius. If we replace the conductor by a thin walled tube
        /// of radius GMR, then its reactance is identical to the reactance of the
        /// actual conductor.
        /// </summary>
        [Column("gmr")]
        public double? Gmr { get; set; }
        /// <summary>
        /// True if conductor is insulated.
        /// </summary>
        [Column("insulated")]
        public bool? Insulated { get; set; }
        /// <summary>
        /// (if insulated conductor) Material used for insulation.
        /// </summary>
        [Column("insulationMaterial")]
        [MaxLength(100)]
        public string? InsulationMaterial { get; set; }
        /// <summary>
        /// (if insulated conductor) Thickness of the insulation.
        /// </summary>
        [Column("insulationThickness")]
        public double? InsulationThickness { get; set; }
        /// <summary>
        /// Conductor material.
        /// </summary>
        [Column("material")]
        [MaxLength(100)]
        public string? Material { get; set; }
    }
    /// <summary>
    /// Wire spacing data that associates multiple wire positions with the line
    /// segment, and allows to calculate line segment impedances. Number of phases
    /// can be derived from the number of associated wire positions whose phase
    /// is not neutral.
    /// </summary>
    [Table("WireSpacingInfo")]
    public class WireSpacingInfo : AssetInfo
    {
        // Inherits from AssetInfo - configure further in EF Fluent API if needed
        public WireSpacingInfo() { }
        public override string ToString() { return this.GetType().Name; }
    }
    /// <summary>
    /// Overhead wire data.
    /// </summary>
    [Table("OverheadWireInfo")]
    public class OverheadWireInfo : WireInfo
    {
        // Inherits from WireInfo - configure further in EF Fluent API if needed
        public OverheadWireInfo() { }
        public override string ToString() { return this.GetType().Name; }
    }
    public static readonly System.Type[] allClasses = new System.Type[]
    {
        typeof(CrewStatusKind),
        typeof(PhaseCode),
        typeof(ShuntImpedanceControlKind),
        typeof(ShuntImpedanceLocalControlKind),
        typeof(WireInsulationKind),
        typeof(WireMaterialKind),
        typeof(ElectronicAddress),
        typeof(Status),
        typeof(StreetDetail),
        typeof(TelephoneNumber),
        typeof(TownDetail),
        typeof(StreetAddress),
        typeof(IdentifiedObject),
        typeof(ShuntCompensatorControl),
        typeof(AssetInfo),
        typeof(Organisation),
        typeof(ParentOrganization),
        typeof(ShuntCompensatorInfo),
        typeof(WireInfo),
        typeof(WireSpacingInfo),
        typeof(OverheadWireInfo)
    };
    /// <summary>
    /// Generated EF Core Fluent API configuration for the SampleProfile profile.
    /// Apply this from your hand-written DbContext.OnModelCreating override - see the
    /// file header comment for the recommended usage pattern.
    /// This class is fully regenerated by CIMTool - do not edit manually.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Cascade vs ClientNoAction Delete Behavior</b><br/>
    /// Two distinct <c>DeleteBehavior</c> values are configured depending on
    /// relationship kind:
    /// <list type="bullet">
    ///    <item>
    ///      <c>DeleteBehavior.Cascade</c> - CIM Compound type references
    ///      (e.g. <c>ElectronicAddress</c>, <c>Status</c>, <c>TelephoneNumber</c>).
    ///      Compound rows are value objects with exactly one owner. The companion
    ///      SQL DDL emits <c>ON DELETE CASCADE</c> for these FKs.
    ///      <c>DeleteBehavior.Cascade</c> keeps EF Core's relationship metadata and
    ///      tracked graph behavior aligned, but it does not by itself implement
    ///      owner-side orphan cleanup when the FK column is stored on the owner row.
    ///      Applications that need exact compound ownership cleanup should add a
    ///      <c>SaveChanges</c> override or interceptor.
    ///    </item>
    ///    <item>
    ///      <c>DeleteBehavior.ClientNoAction</c> - associations between independent
    ///      IdentifiedObject entities. These carry no DB-level cascade and deleting
    ///      one end must not silently delete the other. Cascade responsibility is
    ///      left entirely to the application.
    ///    </item>
    ///  </list>
    /// </para>
    /// </remarks>
    public static class ModelConfiguration
    {
        public static void ConfigureModel(ModelBuilder modelBuilder)
        {
            ConfigureCrewStatusKind(modelBuilder);
            ConfigurePhaseCode(modelBuilder);
            ConfigureShuntImpedanceControlKind(modelBuilder);
            ConfigureShuntImpedanceLocalControlKind(modelBuilder);
            ConfigureWireInsulationKind(modelBuilder);
            ConfigureWireMaterialKind(modelBuilder);
            ConfigureElectronicAddress(modelBuilder);
            ConfigureStatus(modelBuilder);
            ConfigureStreetDetail(modelBuilder);
            ConfigureTelephoneNumber(modelBuilder);
            ConfigureTownDetail(modelBuilder);
            ConfigureStreetAddress(modelBuilder);
            ConfigureIdentifiedObject(modelBuilder);
            ConfigureShuntCompensatorControl(modelBuilder);
            ConfigureAssetInfo(modelBuilder);
            ConfigureOrganisation(modelBuilder);
            ConfigureParentOrganization(modelBuilder);
            ConfigureShuntCompensatorInfo(modelBuilder);
            ConfigureWireInfo(modelBuilder);
            ConfigureWireSpacingInfo(modelBuilder);
            ConfigureOverheadWireInfo(modelBuilder);
        }
        private static void ConfigureCrewStatusKind(ModelBuilder modelBuilder)
        => modelBuilder.Entity<CrewStatusKind>().ToTable("CrewStatusKind");
        private static void ConfigurePhaseCode(ModelBuilder modelBuilder)
        => modelBuilder.Entity<PhaseCode>().ToTable("PhaseCode");
        private static void ConfigureShuntImpedanceControlKind(ModelBuilder modelBuilder)
        => modelBuilder.Entity<ShuntImpedanceControlKind>().ToTable("ShuntImpedanceControlKind");
        private static void ConfigureShuntImpedanceLocalControlKind(ModelBuilder modelBuilder)
        => modelBuilder.Entity<ShuntImpedanceLocalControlKind>().ToTable("ShuntImpedanceLocalControlKind");
        private static void ConfigureWireInsulationKind(ModelBuilder modelBuilder)
        => modelBuilder.Entity<WireInsulationKind>().ToTable("WireInsulationKind");
        private static void ConfigureWireMaterialKind(ModelBuilder modelBuilder)
        => modelBuilder.Entity<WireMaterialKind>().ToTable("WireMaterialKind");
        private static void ConfigureElectronicAddress(ModelBuilder modelBuilder)
        => modelBuilder.Entity<ElectronicAddress>().ToTable("ElectronicAddress");
        private static void ConfigureStatus(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Status>().ToTable("Status");
        private static void ConfigureStreetDetail(ModelBuilder modelBuilder)
        => modelBuilder.Entity<StreetDetail>().ToTable("StreetDetail");
        private static void ConfigureTelephoneNumber(ModelBuilder modelBuilder)
        => modelBuilder.Entity<TelephoneNumber>().ToTable("TelephoneNumber");
        private static void ConfigureTownDetail(ModelBuilder modelBuilder)
        => modelBuilder.Entity<TownDetail>().ToTable("TownDetail");
        private static void ConfigureStreetAddress(ModelBuilder modelBuilder)
        {
            var e = modelBuilder.Entity<StreetAddress>();
            e.ToTable("StreetAddress");
            e.HasOne(x => x.Status).WithMany().HasForeignKey(x => x.StatusId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.StreetDetail).WithMany().HasForeignKey(x => x.StreetDetailId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.TownDetail).WithMany().HasForeignKey(x => x.TownDetailId).OnDelete(DeleteBehavior.Cascade);
        }
        private static void ConfigureIdentifiedObject(ModelBuilder modelBuilder)
        => modelBuilder.Entity<IdentifiedObject>().ToTable("IdentifiedObject");
        private static void ConfigureShuntCompensatorControl(ModelBuilder modelBuilder)
        => modelBuilder.Entity<ShuntCompensatorControl>().ToTable("ShuntCompensatorControl");
        private static void ConfigureAssetInfo(ModelBuilder modelBuilder)
        => modelBuilder.Entity<AssetInfo>().ToTable("AssetInfo");
        private static void ConfigureOrganisation(ModelBuilder modelBuilder)
        {
            var e = modelBuilder.Entity<Organisation>();
            e.ToTable("Organisation");
            e.HasOne(x => x.ElectronicAddress).WithMany().HasForeignKey(x => x.ElectronicAddressId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.ParentOrganisation).WithMany().HasForeignKey(x => x.ParentOrganisationId).OnDelete(DeleteBehavior.ClientNoAction);
            e.HasOne(x => x.Phone1).WithMany().HasForeignKey(x => x.Phone1Id).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.Phone2).WithMany().HasForeignKey(x => x.Phone2Id).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.PostalAddress).WithMany().HasForeignKey(x => x.PostalAddressId).OnDelete(DeleteBehavior.Cascade);
            e.HasOne(x => x.StreetAddress).WithMany().HasForeignKey(x => x.StreetAddressId).OnDelete(DeleteBehavior.Cascade);
        }
        private static void ConfigureParentOrganization(ModelBuilder modelBuilder)
        => modelBuilder.Entity<ParentOrganization>().ToTable("ParentOrganization");
        private static void ConfigureShuntCompensatorInfo(ModelBuilder modelBuilder)
        {
            var e = modelBuilder.Entity<ShuntCompensatorInfo>();
            e.ToTable("ShuntCompensatorInfo");
            e.HasOne(x => x.ShuntCompensatorControl).WithMany().HasForeignKey(x => x.ShuntCompensatorControlId).OnDelete(DeleteBehavior.ClientNoAction);
        }
        private static void ConfigureWireInfo(ModelBuilder modelBuilder)
        => modelBuilder.Entity<WireInfo>().ToTable("WireInfo");
        private static void ConfigureWireSpacingInfo(ModelBuilder modelBuilder)
        => modelBuilder.Entity<WireSpacingInfo>().ToTable("WireSpacingInfo");
        private static void ConfigureOverheadWireInfo(ModelBuilder modelBuilder)
        => modelBuilder.Entity<OverheadWireInfo>().ToTable("OverheadWireInfo");
    }
}
