package io.ucaiug.cimtool.generated;
import jakarta.persistence.*;
import java.time.*;
import java.util.*;
/**
 * Annotated Java for the SampleProfile profile.
 * Generated by CIMTool https://cimtool.ucaiug.io
 * 
 * JPA Version: Jakarta Persistence 3.1 (Jakarta EE 10)
 * 
 * Inheritance Strategy
 *   All entity hierarchies use JOINED table-per-type inheritance, matching
 *   the SQL DDL schema generated by the companion sql-rdfs-ansi92 builder.
 *   Each class maps to its own table joined on the primary key.
 * 
 * Class Ordering — Topological Sort
 *   Entity classes and the allClasses array are emitted in inheritance-safe
 *   topological order using Kahn's algorithm, ensuring every superclass
 *   appears before its subclasses. EnumeratedTypes are always emitted first
 *   as they have no dependencies. ComplexType and Root classes follow in
 *   inheritance-sorted order.
 *   
 *   Note: only the SuperType (inheritance) chain is used for ordering — FK
 *   associations are intentionally excluded. Java allows forward class
 *   references within a single compilation unit, so FK association order
 *   is irrelevant for class declarations. Including FK associations in the
 *   dependency graph creates cycles in profiles with dense association
 *   networks (e.g. CGMES) that cause 40+ classes to fall back to document
 *   order — precisely the problem this sort is designed to prevent.
 * 
 * IdentifiedObject Hierarchy vs Non-IdentifiedObject Classes
 *   Classes that inherit from IdentifiedObject use a natural String mRID
 *   primary key mapped to @Id @Column(name="mRID").
 *   Classes that do NOT inherit from IdentifiedObject (e.g. CurveData,
 *   TapChangerTablePoint, Quality61850) use a surrogate UUID primary key
 *   mapped to @Id @GeneratedValue(strategy=GenerationType.UUID) with
 *   @Column(name="id"). The UUID is auto-generated by the JPA provider
 *   on persist, consistent with the companion SQL DDL schema.
 * 
 * FK Column Indexes
 *   All single-valued FK associations (a:Instance, a:Reference, a:Compound)
 *   receive a corresponding @Index entry on the @Table annotation. This
 *   mirrors exactly the CREATE INDEX statements emitted by the companion
 *   sql-rdfs-ansi92 builder, using the same naming convention:
 *   
 *     ix_{tableName}_{columnName}
 *   
 *   For example:
 *     CREATE INDEX ix_Equipment_EquipmentContainer ...
 *   becomes:
 *     @Index(name="ix_Equipment_EquipmentContainer", columnList="EquipmentContainer")
 *   
 *   Consistent naming ensures schema validation (hbm2ddl.auto=validate)
 *   finds the expected index names in the database. Compound FK columns
 *   are also indexed even though they already carry a UNIQUE constraint —
 *   this maintains exact parity with the SQL DDL builder.
 * 
 * Heuristic Unique Constraints for Non-IdentifiedObject Classes
 *   Non-IdentifiedObject entity classes (those using a surrogate UUID @Id)
 *   receive a @UniqueConstraint on their @Table annotation spanning all
 *   required (minOccurs=1) non-surrogate columns — both scalar attributes
 *   and required single-valued FK associations. This mirrors the heuristic
 *   UNIQUE constraint emitted by the companion sql-rdfs-ansi92 builder:
 *   
 *     ALTER TABLE "CurveData" ADD UNIQUE ("xvalue", "y1value", "Curve");
 *   
 *   becomes in JPA:
 *     @Table(name="CurveData", uniqueConstraints = {
 *       @UniqueConstraint(columnNames = {"xvalue", "y1value", "Curve"})
 *     })
 *   
 *   The constraint may be wider than the true natural key (which is only
 *   known from the IEC specification prose, not from the profile catalog
 *   XML) but is never incorrect — a wider UNIQUE prevents valid duplicate
 *   insertion; a missing UNIQUE permits silent semantic corruption.
 *   IdentifiedObject subclasses are not affected — their natural mRID PK
 *   is the authoritative unique identifier and needs no additional guard.
 * 
 * Boolean Column Mapping
 *   CIM boolean attributes (xstype="boolean") map to Java Boolean and are
 *   annotated with @Column(columnDefinition="INTEGER DEFAULT 0"). Without
 *   this hint most JPA providers create a BOOLEAN or BIT column, which does
 *   not match the companion sql-rdfs-ansi92 builder's schema:
 *   
 *     "enabled" INTEGER DEFAULT 0 CHECK ("enabled" IN (0, 1))
 *   
 *   The columnDefinition aligns the JPA-managed schema with the SQL DDL.
 *   Required booleans (minOccurs=1) additionally carry nullable=false,
 *   matching the NOT NULL emitted by the SQL DDL builder for those columns.
 *   
 *   Oracle portability note: columnDefinition="INTEGER DEFAULT 0" is passed
 *   verbatim to the RDBMS during JPA schema generation. On Oracle, INTEGER
 *   maps to NUMBER(38) rather than the idiomatic NUMBER(1). If targeting
 *   Oracle and using JPA schema generation, override columnDefinition to
 *   NUMBER(1) DEFAULT 0 in a subclass or use a custom AttributeConverter.
 *   This concern does not apply when using the companion sql-rdfs-ansi92
 *   DDL script for schema creation (the recommended approach) — in that
 *   case the columnDefinition hint is advisory only and never executed.
 * 
 * Requirements related to equals() and hashCode()
 *   All entity classes include generated equals() and hashCode()
 *   implementations following the Mihalcea portable JPA pattern:
 *   
 *     - equals() uses getClass() rather than instanceof to correctly
 *       handle Hibernate proxy objects. instanceof would pass for the
 *       proxy-to-real direction but fail in reverse, causing subtle bugs
 *       when entities are stored in collections.
 *     
 *     - hashCode() returns getClass().hashCode() — a fixed constant per
 *       class. This ensures hash stability across the transient-to-
 *       persistent lifecycle before the JPA provider assigns the key.
 *     
 *     - equals() compares on the natural key only when non-null, so two
 *       unsaved (transient) instances are never considered equal.
 *   
 *   Generated on hierarchy roots only — subclasses inherit:
 *     - IdentifiedObject root: key = mRID (String)
 *     - Non-IdentifiedObject roots: key = id (UUID)
 *     - CompoundType classes: key = id (UUID)
 *     - EnumeratedType classes: key = name (String)
 *   
 *   Reference: Vlad Mihalcea, "The Best Way to Implement equals and
 *   hashCode with JPA":
 *     https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
 * 
 * @Inheritance on Non-IdentifiedObject Classes
 *   The @Inheritance(strategy=InheritanceType.JOINED) annotation is
 *   only emitted on non-IdentifiedObject root classes that have at
 *   least one subclass present in this profile. Leaf classes with no
 *   subclasses (e.g. CurveData, RegularTimePoint) are emitted without
 *   @Inheritance — it would be misleading to the JPA provider and
 *   adds no functional value for a class that is never extended.
 *   IdentifiedObject is always emitted with @Inheritance since it is
 *   by definition the root of the entire entity hierarchy.
 * 
 * No @OneToMany Mappings — Intentional Design
 *   Collection associations (maxOccurs=unbounded, i.e. the one side of a
 *   one-to-many relationship) are intentionally NOT mapped as @OneToMany.
 *   The @ManyToOne on the child side is sufficient for all JPA operations.
 *   This is a deliberate architectural choice, not an omission. Developers
 *   who expect @OneToMany collection properties should read this section
 *   before adding them manually.
 *   
 *   Rationale:
 *     - @OneToMany requires a mappedBy string that is not validated at
 *       compile time. A mismatch fails silently and throws an obscure
 *       AnnotationException at JPA provider bootstrap, which is difficult
 *       to diagnose in generated code.
 *     - CIM associations are unbounded by definition. Loading an unbounded
 *       collection into memory with no pagination is a runtime hazard for
 *       large profiles such as CGMES CoreEquipment, where an equipment
 *       container may have thousands of children. Hibernate will issue a
 *       single SELECT with no LIMIT, materialising the entire result set.
 *     - Bidirectional @OneToMany requires both sides to be kept in sync
 *       on every add and remove operation. Failing to do so causes
 *       inconsistent in-memory state and subtle persistence bugs that
 *       are notoriously difficult to reproduce and debug.
 *     - Bidirectional mappings with CascadeType.ALL or orphanRemoval=true
 *       interact unpredictably with the compound value object cascade
 *       semantics already present in this generated code, risking
 *       accidental deletion of entities that should remain.
 *     - Inverse associations are profile-dependent and not present in all
 *       profiles, making generated @OneToMany properties inconsistent
 *       across profiles and creating a false expectation of completeness.
 *     - Explicit JPQL queries support pagination, filtering, and sorting
 *       that a generated collection property never can, and make the
 *       data access intent explicit rather than implicit.
 *   
 *   To navigate from a parent entity to its children, use a JPQL query.
 *   Query through the child side via the @ManyToOne FK field. This keeps
 *   all data access explicit, pageable, and safe for large result sets:
 *   
 *     // Find all PowerElectronicsUnit instances for a given connection:
 *     List<PowerElectronicsUnit> units = em.createQuery(
 *       "SELECT u FROM PowerElectronicsUnit u " +
 *       "WHERE u.powerElectronicsConnection = :conn", PowerElectronicsUnit.class)
 *         .setParameter("conn", connection)
 *         .getResultList();
 *     
 *     // With pagination for large result sets:
 *     List<Equipment> equipment = em.createQuery(
 *       "SELECT e FROM Equipment e " +
 *       "WHERE e.equipmentContainer = :container", Equipment.class)
 *         .setParameter("container", substation)
 *         .setFirstResult(0)
 *         .setMaxResults(100)
 *         .getResultList();
 *   
 *   References:
 *     Vlad Mihalcea, "The Best Way to Map a @OneToMany Relationship
 *     with JPA and Hibernate":
 *     https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/
 *     
 *     Vlad Mihalcea, "The Best Way to Use the @ManyToOne Annotation":
 *     https://vladmihalcea.com/manytoone-jpa-hibernate/
 * 
 * Compound Type References
 *   CIM Compound types are value objects — each compound row has exactly
 *   one owner (the specific parent column on the specific parent row that
 *   caused its creation) and is never shared. They are represented as
 *   separate @Entity classes with a surrogate UUID @Id auto-generated by
 *   the JPA provider on persist via @GeneratedValue(strategy=UUID).
 *   
 *   Compound references on parent entities use:
 *     @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
 *     @JoinColumn(name="compoundColumnName")
 *   
 *   CascadeType.REMOVE implements the value object ownership model —
 *   when a parent entity is deleted, its compound child entities are
 *   automatically deleted by the JPA provider, consistent with the
 *   ON DELETE CASCADE constraints in the companion SQL DDL script.
 *   
 *   Compound surrogate key UUID assignment is handled automatically by
 *   the JPA provider via @GeneratedValue — no application-level UUID
 *   generation code is required. See the companion sql-rdfs-ansi92 DDL
 *   script header for full details on the value object ownership model
 *   and the UUID generation directive.
 * 
 * JPA Integration
 *   This file includes complete JPA 3.1 annotations on all generated entity
 *   classes. Unlike C#'s Entity Framework (EF) Core which requires explicit
 *   ModelConfiguration registration, JPA discovers all mappings — relationships,
 *   column definitions, inheritance strategy, and cascade behaviour — directly
 *   from the annotations on the generated classes. No additional configuration
 *   method needs to be called.
 *   
 *   To integrate these entities into a JPA application, define a persistence
 *   unit in META-INF/persistence.xml. The allClasses array at the bottom of
 *   this file provides the complete list of entity classes for this profile.
 *   For profiles with many classes, package scanning is strongly preferred
 *   over explicit <class> entries — maintaining 100+ class entries manually
 *   is impractical and any regeneration would require reconciling the list.
 *   
 *   Note: all generated entity classes are static inner classes of the outer
 *   SampleProfile class. When using explicit <class> entries in persistence.xml
 *   use the $ separator, e.g.:
 *   
 *     io.ucaiug.cimtool.generated.SampleProfile$IdentifiedObject
 *   
 *   Hibernate 6.x (JPA 3.1 reference implementation):
 *     <persistence-unit name="SampleProfile" transaction-type="RESOURCE_LOCAL">
 *       <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
 *       <jar-file>cim-entities.jar</jar-file>
 *       <exclude-unlisted-classes>false</exclude-unlisted-classes>
 *       <properties>
 *         <property name="jakarta.persistence.jdbc.url" value="jdbc:..."/>
 *         <property name="hibernate.hbm2ddl.auto" value="validate"/>
 *       </properties>
 *     </persistence-unit>
 *   
 *   EclipseLink (default provider in GlassFish, Payara):
 *     <persistence-unit name="SampleProfile" transaction-type="RESOURCE_LOCAL">
 *       <provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
 *       <jar-file>cim-entities.jar</jar-file>
 *       <properties>
 *         <property name="jakarta.persistence.jdbc.url" value="jdbc:..."/>
 *         <property name="eclipselink.ddl-generation" value="none"/>
 *       </properties>
 *     </persistence-unit>
 *   
 *   OpenJPA (Apache TomEE):
 *     <persistence-unit name="SampleProfile" transaction-type="RESOURCE_LOCAL">
 *       <provider>org.apache.openjpa.persistence.PersistenceProviderImpl</provider>
 *       <jar-file>cim-entities.jar</jar-file>
 *     </persistence-unit>
 *   
 *   Standalone Java application (any provider):
 *     // Use the EntityManagerFactory directly via Persistence.createEntityManagerFactory.
 *     // This is the most portable approach and works with any JPA provider on the classpath.
 *     
 *     import jakarta.persistence.*;
 *     
 *     EntityManagerFactory emFactory = Persistence.createEntityManagerFactory("SampleProfile");
 *     try {
 *       EntityManager em = emf.createEntityManager();
 *       em.getTransaction().begin();
 *       // ... work with entities ...
 *       em.getTransaction().commit();
 *     }
 *     finally {
 *       em.close();
 *     }
 *     emFactory.close()
 *   
 *   Spring Boot:
 *     @SpringBootApplication
 *     @EntityScan("io.ucaiug.cimtool.generated")
 *     public class CimRepository {
 *       @PersistenceContext(unitName = "SampleProfile")
 *       private EntityManager em;
 *     }
 *     
 *     // application.yml:
 *     spring.jpa.hibernate.ddl-auto: validate
 *   
 *   Quarkus:
 *     // application.properties:
 *     quarkus.hibernate-orm.packages=io.ucaiug.cimtool.generated
 *     quarkus.hibernate-orm.database.generation=none
 *   
 *   Jakarta EE application server (WildFly, Payara, WebLogic):
 *     Use container-managed transactions and @PersistenceContext injection.
 *     Set transaction-type="JTA" with <jta-data-source> in persistence.xml.
 *     On servers with strict classloading (WebLogic, older WebSphere), use
 *     explicit <class> entries or <jar-file> rather than package scanning.
 *     
 *     @Stateless
 *     public class CimRepository {
 *       @PersistenceContext(unitName = "SampleProfile")
 *       private EntityManager em;
 *     }
 *   
 * Schema Generation Warning
 *   The companion sql-rdfs-ansi92 DDL script is the authoritative schema and
 *   should always be used for production schema creation. JPA auto DDL
 *   generation (hbm2ddl.auto, ddl-generation, etc.) will not reproduce:
 *   
 *     - INTEGER DEFAULT 0 CHECK ("col" IN (0,1)) for boolean columns
 *     - Heuristic UNIQUE constraints on non-IdentifiedObject tables
 *     - Reverse-reference ON DELETE CASCADE for compound value objects
 *   
 *   Set ddl-generation/hbm2ddl.auto to "validate" or "none" in all
 *   environments where the SQL DDL script has been applied.
 */
public class SampleProfile {
    
    /**
     * Defines the current status of the Crew - assigned, arrived, etc.
     */
    @Entity
    @Table(name="CrewStatusKind")
    public static class CrewStatusKind {
        @Id
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            CrewStatusKind that = (CrewStatusKind) o;
            return name != null && name.equals(that.name);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
    };
    
    /**
     * An unordered enumeration of phase identifiers. Allows designation of phases
     * for both transmission and distribution equipment, circuits and loads. The
     * enumeration, by itself, does not describe how the phases are connected
     * together or connected to ground. Ground is not explicitly denoted as a
     * phase.
     * Residential and small commercial loads are often served from single-phase,
     * or split-phase, secondary circuits. For the example of s12N, phases 1 and
     * 2 refer to hot wires that are 180 degrees out of phase, while N refers
     * to the neutral wire. Through single-phase transformer connections, these
     * secondary circuits may be served from one or two of the primary phases
     * A, B, and C. For three-phase loads, use the A, B, C phase codes instead
     * of s12N.
     * The integer values are from IEC 61968-9 to support revenue metering applications.
     */
    @Entity
    @Table(name="PhaseCode")
    public static class PhaseCode {
        @Id
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            PhaseCode that = (PhaseCode) o;
            return name != null && name.equals(that.name);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
    };
    
    /**
     * Kind of wire insulation.
     */
    @Entity
    @Table(name="WireInsulationKind")
    public static class WireInsulationKind {
        @Id
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            WireInsulationKind that = (WireInsulationKind) o;
            return name != null && name.equals(that.name);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
    };
    
    /**
     * Kind of wire material.
     */
    @Entity
    @Table(name="WireMaterialKind")
    public static class WireMaterialKind {
        @Id
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            WireMaterialKind that = (WireMaterialKind) o;
            return name != null && name.equals(that.name);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
    };
    
    /**
     * Electronic address information.
     */
    @Entity
    @Table(name="ElectronicAddress")
    public static class ElectronicAddress {
        
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            ElectronicAddress that = (ElectronicAddress) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * Primary email address.
         */
        @Column(name="email1")
        private String email1;
        
        public String getEmail1() {
            return email1;
        }
        
        public void setEmail1(String email1) {
            this.email1 = email1;
        }
        
        /**
         * Alternate email address.
         */
        @Column(name="email2")
        private String email2;
        
        public String getEmail2() {
            return email2;
        }
        
        public void setEmail2(String email2) {
            this.email2 = email2;
        }
        
        /**
         * Address on local area network.
         */
        @Column(name="lan")
        private String lan;
        
        public String getLan() {
            return lan;
        }
        
        public void setLan(String lan) {
            this.lan = lan;
        }
        
        /**
         * MAC (Media Access Control) address.
         */
        @Column(name="mac")
        private String mac;
        
        public String getMac() {
            return mac;
        }
        
        public void setMac(String mac) {
            this.mac = mac;
        }
        
        /**
         * Password needed to log in.
         */
        @Column(name="password")
        private String password;
        
        public String getPassword() {
            return password;
        }
        
        public void setPassword(String password) {
            this.password = password;
        }
        
        /**
         * Radio address.
         */
        @Column(name="radio")
        private String radio;
        
        public String getRadio() {
            return radio;
        }
        
        public void setRadio(String radio) {
            this.radio = radio;
        }
        
        /**
         * User ID needed to log in, which can be for an individual person, an organisation,
         * a location, etc.
         */
        @Column(name="userID")
        private String userID;
        
        public String getUserID() {
            return userID;
        }
        
        public void setUserID(String userID) {
            this.userID = userID;
        }
        
        /**
         * World wide web address.
         */
        @Column(name="web")
        private String web;
        
        public String getWeb() {
            return web;
        }
        
        public void setWeb(String web) {
            this.web = web;
        }
    }
    
    /**
     * Current status information relevant to an entity.
     */
    @Entity
    @Table(name="Status")
    public static class Status {
        
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Status that = (Status) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * Date and time for which status 'value' applies.
         */
        @Column(name="dateTime")
        private LocalDateTime dateTime;
        
        public LocalDateTime getDateTime() {
            return dateTime;
        }
        
        public void setDateTime(LocalDateTime dateTime) {
            this.dateTime = dateTime;
        }
        
        /**
         * Reason code or explanation for why an object went to the current status
         * 'value'.
         */
        @Column(name="reason")
        private String reason;
        
        public String getReason() {
            return reason;
        }
        
        public void setReason(String reason) {
            this.reason = reason;
        }
        
        /**
         * Pertinent information regarding the current 'value', as free form text.
         */
        @Column(name="remark")
        private String remark;
        
        public String getRemark() {
            return remark;
        }
        
        public void setRemark(String remark) {
            this.remark = remark;
        }
        
        /**
         * Status value at 'dateTime'; prior status changes may have been kept in
         * instances of activity records associated with the object to which this
         * status applies.
         */
        @Column(name="value")
        private String value;
        
        public String getValue() {
            return value;
        }
        
        public void setValue(String value) {
            this.value = value;
        }
    }
    
    /**
     * Street details, in the context of address.
     */
    @Entity
    @Table(name="StreetDetail")
    public static class StreetDetail {
        
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            StreetDetail that = (StreetDetail) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * First line of a free form address or some additional address information
         * (for example a mail stop).
         */
        @Column(name="addressGeneral")
        private String addressGeneral;
        
        public String getAddressGeneral() {
            return addressGeneral;
        }
        
        public void setAddressGeneral(String addressGeneral) {
            this.addressGeneral = addressGeneral;
        }
        
        /**
         * (if applicable) Second line of a free form address.
         */
        @Column(name="addressGeneral2")
        private String addressGeneral2;
        
        public String getAddressGeneral2() {
            return addressGeneral2;
        }
        
        public void setAddressGeneral2(String addressGeneral2) {
            this.addressGeneral2 = addressGeneral2;
        }
        
        /**
         * (if applicable) Third line of a free form address.
         */
        @Column(name="addressGeneral3")
        private String addressGeneral3;
        
        public String getAddressGeneral3() {
            return addressGeneral3;
        }
        
        public void setAddressGeneral3(String addressGeneral3) {
            this.addressGeneral3 = addressGeneral3;
        }
        
        /**
         * (if applicable) In certain cases the physical location of the place of
         * interest does not have a direct point of entry from the street, but may
         * be located inside a larger structure such as a building, complex, office
         * block, apartment, etc.
         */
        @Column(name="buildingName")
        private String buildingName;
        
        public String getBuildingName() {
            return buildingName;
        }
        
        public void setBuildingName(String buildingName) {
            this.buildingName = buildingName;
        }
        
        /**
         * (if applicable) Utilities often make use of external reference systems,
         * such as those of the town-planner's department or surveyor general's mapping
         * system, that allocate global reference codes to streets.
         */
        @Column(name="code")
        private String code;
        
        public String getCode() {
            return code;
        }
        
        public void setCode(String code) {
            this.code = code;
        }
        
        /**
         * The identification by name or number, expressed as text, of the floor in
         * the building as part of this address.
         */
        @Column(name="floorIdentification")
        private String floorIdentification;
        
        public String getFloorIdentification() {
            return floorIdentification;
        }
        
        public void setFloorIdentification(String floorIdentification) {
            this.floorIdentification = floorIdentification;
        }
        
        /**
         * Name of the street.
         */
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        /**
         * Designator of the specific location on the street.
         */
        @Column(name="number")
        private String number;
        
        public String getNumber() {
            return number;
        }
        
        public void setNumber(String number) {
            this.number = number;
        }
        
        /**
         * Prefix to the street name. For example: North, South, East, West.
         */
        @Column(name="prefix")
        private String prefix;
        
        public String getPrefix() {
            return prefix;
        }
        
        public void setPrefix(String prefix) {
            this.prefix = prefix;
        }
        
        /**
         * Suffix to the street name. For example: North, South, East, West.
         */
        @Column(name="suffix")
        private String suffix;
        
        public String getSuffix() {
            return suffix;
        }
        
        public void setSuffix(String suffix) {
            this.suffix = suffix;
        }
        
        /**
         * Number of the apartment or suite.
         */
        @Column(name="suiteNumber")
        private String suiteNumber;
        
        public String getSuiteNumber() {
            return suiteNumber;
        }
        
        public void setSuiteNumber(String suiteNumber) {
            this.suiteNumber = suiteNumber;
        }
        
        /**
         * Type of street. Examples include: street, circle, boulevard, avenue, road,
         * drive, etc.
         */
        @Column(name="type")
        private String type;
        
        public String getType() {
            return type;
        }
        
        public void setType(String type) {
            this.type = type;
        }
        
        /**
         * True if this street is within the legal geographical boundaries of the
         * specified town (default).
         */
        @Column(name="withinTownLimits", columnDefinition="INTEGER DEFAULT 0")
        private Boolean withinTownLimits;
        
        public Boolean getWithinTownLimits() {
            return withinTownLimits;
        }
        
        public void setWithinTownLimits(Boolean withinTownLimits) {
            this.withinTownLimits = withinTownLimits;
        }
    }
    
    /**
     * Telephone number.
     */
    @Entity
    @Table(name="TelephoneNumber")
    public static class TelephoneNumber {
        
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            TelephoneNumber that = (TelephoneNumber) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * (if applicable) Area or region code.
         */
        @Column(name="areaCode")
        private String areaCode;
        
        public String getAreaCode() {
            return areaCode;
        }
        
        public void setAreaCode(String areaCode) {
            this.areaCode = areaCode;
        }
        
        /**
         * City code.
         */
        @Column(name="cityCode")
        private String cityCode;
        
        public String getCityCode() {
            return cityCode;
        }
        
        public void setCityCode(String cityCode) {
            this.cityCode = cityCode;
        }
        
        /**
         * Country code.
         */
        @Column(name="countryCode")
        private String countryCode;
        
        public String getCountryCode() {
            return countryCode;
        }
        
        public void setCountryCode(String countryCode) {
            this.countryCode = countryCode;
        }
        
        /**
         * (if applicable) Dial out code, for instance to call outside an enterprise.
         */
        @Column(name="dialOut")
        private String dialOut;
        
        public String getDialOut() {
            return dialOut;
        }
        
        public void setDialOut(String dialOut) {
            this.dialOut = dialOut;
        }
        
        /**
         * (if applicable) Extension for this telephone number.
         */
        @Column(name="extension")
        private String extension;
        
        public String getExtension() {
            return extension;
        }
        
        public void setExtension(String extension) {
            this.extension = extension;
        }
        
        /**
         * (if applicable) Prefix used when calling an international number.
         */
        @Column(name="internationalPrefix")
        private String internationalPrefix;
        
        public String getInternationalPrefix() {
            return internationalPrefix;
        }
        
        public void setInternationalPrefix(String internationalPrefix) {
            this.internationalPrefix = internationalPrefix;
        }
        
        /**
         * Phone number according to International Telecommunication Union (ITU) E.164.
         */
        @Column(name="ituPhone")
        private String ituPhone;
        
        public String getItuPhone() {
            return ituPhone;
        }
        
        public void setItuPhone(String ituPhone) {
            this.ituPhone = ituPhone;
        }
        
        /**
         * Main (local) part of this telephone number.
         */
        @Column(name="localNumber")
        private String localNumber;
        
        public String getLocalNumber() {
            return localNumber;
        }
        
        public void setLocalNumber(String localNumber) {
            this.localNumber = localNumber;
        }
    }
    
    /**
     * Town details, in the context of address.
     */
    @Entity
    @Table(name="TownDetail")
    public static class TownDetail {
        
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            TownDetail that = (TownDetail) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * Town code.
         */
        @Column(name="code")
        private String code;
        
        public String getCode() {
            return code;
        }
        
        public void setCode(String code) {
            this.code = code;
        }
        
        /**
         * Name of the country.
         */
        @Column(name="country")
        private String country;
        
        public String getCountry() {
            return country;
        }
        
        public void setCountry(String country) {
            this.country = country;
        }
        
        /**
         * Town name.
         */
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        /**
         * Town section. For example, it is common for there to be 36 sections per
         * township.
         */
        @Column(name="section")
        private String section;
        
        public String getSection() {
            return section;
        }
        
        public void setSection(String section) {
            this.section = section;
        }
        
        /**
         * Name of the state or province.
         */
        @Column(name="stateOrProvince")
        private String stateOrProvince;
        
        public String getStateOrProvince() {
            return stateOrProvince;
        }
        
        public void setStateOrProvince(String stateOrProvince) {
            this.stateOrProvince = stateOrProvince;
        }
    }
    
    /**
     * General purpose street and postal address information.
     */
    @Entity
    @Table(name="StreetAddress", indexes = {{ @Index(name="ix_StreetAddress_status", columnList="status"), @Index(name="ix_StreetAddress_streetDetail", columnList="streetDetail"), @Index(name="ix_StreetAddress_townDetail", columnList="townDetail") }})
    public static class StreetAddress {
        
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            StreetAddress that = (StreetAddress) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * The language in which the address is specified, using ISO 639-1 two digit
         * language code.
         */
        @Column(name="language")
        private String language;
        
        public String getLanguage() {
            return language;
        }
        
        public void setLanguage(String language) {
            this.language = language;
        }
        
        /**
         * Post office box.
         */
        @Column(name="poBox")
        private String poBox;
        
        public String getPoBox() {
            return poBox;
        }
        
        public void setPoBox(String poBox) {
            this.poBox = poBox;
        }
        
        /**
         * Postal code for the address.
         */
        @Column(name="postalCode")
        private String postalCode;
        
        public String getPostalCode() {
            return postalCode;
        }
        
        public void setPostalCode(String postalCode) {
            this.postalCode = postalCode;
        }
        /**
         * Status of this address.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="status")
        private Status status;
        
        public Status getStatus() {
            return status;
        }
        
        public void setStatus(Status status) {
            this.status = status;
        }
        /**
         * Street detail.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="streetDetail")
        private StreetDetail streetDetail;
        
        public StreetDetail getStreetDetail() {
            return streetDetail;
        }
        
        public void setStreetDetail(StreetDetail streetDetail) {
            this.streetDetail = streetDetail;
        }
        /**
         * Town detail.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="townDetail")
        private TownDetail townDetail;
        
        public TownDetail getTownDetail() {
            return townDetail;
        }
        
        public void setTownDetail(TownDetail townDetail) {
            this.townDetail = townDetail;
        }
    }
    
    /**
     * This is a root class to provide common identification for all classes needing
     * identification and naming attributes.
     */
    @Entity
    @Table(name="IdentifiedObject")
    @Inheritance(strategy=InheritanceType.JOINED)
    public static class IdentifiedObject {
        
        @Id
        @Column(name="mRID")
        private String mRID;
        
        public String getMRID() {
            return mRID;
        }
        
        public void setMRID(String mRID) {
            this.mRID = mRID;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            IdentifiedObject that = (IdentifiedObject) o;
            return mRID != null && mRID.equals(that.mRID);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * The name is any free human readable and possibly non unique text naming
         * the object.
         */
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
    }
    
    /**
     * The Name class provides the means to define any number of human readable
     * names for an object. A name is <b>not</b> to be used for defining inter-object
     * relationships. For inter-object relationships instead use the object identification
     * 'mRID'.
     */
    @Entity
    @Table(name="Name", indexes = {{ @Index(name="ix_Name_IdentifiedObject", columnList="IdentifiedObject") }})
    public static class Name {
        @Id
        @GeneratedValue(strategy=GenerationType.UUID)
        @Column(name="id")
        private UUID id;
        
        public UUID getId() {
            return id;
        }
        public void setId(UUID id) {
            this.id = id;
        }
        
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Name that = (Name) o;
            return id != null && id.equals(that.id);
        }
        
        @Override
        public int hashCode() {
            return getClass().hashCode();
        }
        
        /**
         * Any free text that name the object.
         */
        @Column(name="name")
        private String name;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        /**
         * Identified object that this name designates.
         */
        @ManyToOne(fetch=FetchType.LAZY)
        @JoinColumn(name="IdentifiedObject")
        private IdentifiedObject identifiedObject;
        
        public IdentifiedObject getIdentifiedObject() {
            return identifiedObject;
        }
        
        public void setIdentifiedObject(IdentifiedObject identifiedObject) {
            this.identifiedObject = identifiedObject;
        }
    }
    
    /**
     * Set of attributes of an asset, representing typical datasheet information
     * of a physical device that can be instantiated and shared in different data
     * exchange contexts:
     * - as attributes of an asset instance (installed or in stock)
     * - as attributes of an asset model (product by a manufacturer)
     * - as attributes of a type asset (generic type of an asset as used in designs/extension
     * planning).
     */
    @Entity
    @Table(name="AssetInfo")
    @PrimaryKeyJoinColumn(name="mRID")
    public static class AssetInfo extends IdentifiedObject {
        
    }
    
    /**
     * Organisation that might have roles as utility, contractor, supplier, manufacturer,
     * customer, etc.
     */
    @Entity
    @Table(name="Organisation", indexes = {{ @Index(name="ix_Organisation_electronicAddress", columnList="electronicAddress"), @Index(name="ix_Organisation_ParentOrganisation", columnList="ParentOrganisation"), @Index(name="ix_Organisation_phone1", columnList="phone1"), @Index(name="ix_Organisation_phone2", columnList="phone2"), @Index(name="ix_Organisation_postalAddress", columnList="postalAddress"), @Index(name="ix_Organisation_streetAddress", columnList="streetAddress") }})
    @PrimaryKeyJoinColumn(name="mRID")
    public static class Organisation extends IdentifiedObject {
        
        /**
         * Electronic address.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="electronicAddress")
        private ElectronicAddress electronicAddress;
        
        public ElectronicAddress getElectronicAddress() {
            return electronicAddress;
        }
        
        public void setElectronicAddress(ElectronicAddress electronicAddress) {
            this.electronicAddress = electronicAddress;
        }
        /**
         * Parent organisation of this organisation.
         */
        @ManyToOne(fetch=FetchType.LAZY)
        @JoinColumn(name="ParentOrganisation")
        private ParentOrganization parentOrganisation;
        
        public ParentOrganization getParentOrganisation() {
            return parentOrganisation;
        }
        
        public void setParentOrganisation(ParentOrganization parentOrganisation) {
            this.parentOrganisation = parentOrganisation;
        }
        /**
         * Phone number.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="phone1")
        private TelephoneNumber phone1;
        
        public TelephoneNumber getPhone1() {
            return phone1;
        }
        
        public void setPhone1(TelephoneNumber phone1) {
            this.phone1 = phone1;
        }
        /**
         * Additional phone number.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="phone2")
        private TelephoneNumber phone2;
        
        public TelephoneNumber getPhone2() {
            return phone2;
        }
        
        public void setPhone2(TelephoneNumber phone2) {
            this.phone2 = phone2;
        }
        /**
         * Postal address, potentially different than 'streetAddress' (e.g., another
         * city).
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="postalAddress")
        private StreetAddress postalAddress;
        
        public StreetAddress getPostalAddress() {
            return postalAddress;
        }
        
        public void setPostalAddress(StreetAddress postalAddress) {
            this.postalAddress = postalAddress;
        }
        /**
         * Street address.
         */
        @ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE)
        @JoinColumn(name="streetAddress")
        private StreetAddress streetAddress;
        
        public StreetAddress getStreetAddress() {
            return streetAddress;
        }
        
        public void setStreetAddress(StreetAddress streetAddress) {
            this.streetAddress = streetAddress;
        }
    }
    
    /**
     */
    @Entity
    @Table(name="ParentOrganization")
    @PrimaryKeyJoinColumn(name="mRID")
    public static class ParentOrganization extends Organisation {
        
    }
    
    /**
     * Wire data that can be specified per line segment phase, or for the line
     * segment as a whole in case its phases all have the same wire characteristics.
     */
    @Entity
    @Table(name="WireInfo")
    @PrimaryKeyJoinColumn(name="mRID")
    public static class WireInfo extends AssetInfo {
        
        
        /**
         * (if there is a different core material) Radius of the central core.
         */
        @Column(name="coreRadius")
        private Double coreRadius;
        
        public Double getCoreRadius() {
            return coreRadius;
        }
        
        public void setCoreRadius(Double coreRadius) {
            this.coreRadius = coreRadius;
        }
        
        /**
         * (if used) Number of strands in the steel core.
         */
        @Column(name="coreStrandCount")
        private Integer coreStrandCount;
        
        public Integer getCoreStrandCount() {
            return coreStrandCount;
        }
        
        public void setCoreStrandCount(Integer coreStrandCount) {
            this.coreStrandCount = coreStrandCount;
        }
        
        /**
         * Geometric mean radius. If we replace the conductor by a thin walled tube
         * of radius GMR, then its reactance is identical to the reactance of the
         * actual conductor.
         */
        @Column(name="gmr")
        private Double gmr;
        
        public Double getGmr() {
            return gmr;
        }
        
        public void setGmr(Double gmr) {
            this.gmr = gmr;
        }
        
        /**
         * True if conductor is insulated.
         */
        @Column(name="insulated", columnDefinition="INTEGER DEFAULT 0")
        private Boolean insulated;
        
        public Boolean getInsulated() {
            return insulated;
        }
        
        public void setInsulated(Boolean insulated) {
            this.insulated = insulated;
        }
        /**
         * (if insulated conductor) Material used for insulation.
         */
        @Column(name="insulationMaterial")
        private String insulationMaterial;
        
        public String getInsulationMaterial() {
            return insulationMaterial;
        }
        
        public void setInsulationMaterial(String insulationMaterial) {
            this.insulationMaterial = insulationMaterial;
        }
        
        /**
         * (if insulated conductor) Thickness of the insulation.
         */
        @Column(name="insulationThickness")
        private Double insulationThickness;
        
        public Double getInsulationThickness() {
            return insulationThickness;
        }
        
        public void setInsulationThickness(Double insulationThickness) {
            this.insulationThickness = insulationThickness;
        }
        /**
         * Conductor material.
         */
        @Column(name="material")
        private String material;
        
        public String getMaterial() {
            return material;
        }
        
        public void setMaterial(String material) {
            this.material = material;
        }
    }
    
    /**
     * Wire spacing data that associates multiple wire positions with the line
     * segment, and allows to calculate line segment impedances. Number of phases
     * can be derived from the number of associated wire positions whose phase
     * is not neutral.
     */
    @Entity
    @Table(name="WireSpacingInfo")
    @PrimaryKeyJoinColumn(name="mRID")
    public static class WireSpacingInfo extends AssetInfo {
        
    }
    
    /**
     * Overhead wire data.
     */
    @Entity
    @Table(name="OverheadWireInfo")
    @PrimaryKeyJoinColumn(name="mRID")
    public static class OverheadWireInfo extends WireInfo {
        
    }
    
    public static final Class[] allClasses = new Class[]
    {
        CrewStatusKind.class,
        PhaseCode.class,
        WireInsulationKind.class,
        WireMaterialKind.class,
        ElectronicAddress.class,
        Status.class,
        StreetDetail.class,
        TelephoneNumber.class,
        TownDetail.class,
        StreetAddress.class,
        IdentifiedObject.class,
        Name.class,
        AssetInfo.class,
        Organisation.class,
        ParentOrganization.class,
        WireInfo.class,
        WireSpacingInfo.class,
        OverheadWireInfo.class
    };
}
